// Autogenerated by convert_tests.py and process_polyglot.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../templates/Test.java
package gen;

import com.rethinkdb.RethinkDB;
import com.rethinkdb.gen.exc.*;
import com.rethinkdb.gen.ast.*;
import com.rethinkdb.ast.ReqlAst;
import com.rethinkdb.model.MapObject;
import com.rethinkdb.model.OptArgs;
import com.rethinkdb.net.Connection;
import com.rethinkdb.net.Cursor;
import junit.framework.TestCase;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertArrayEquals;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.junit.*;
import org.junit.rules.ExpectedException;

import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.Instant;
import java.util.stream.LongStream;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.concurrent.TimeoutException;
import java.util.regex.Pattern;
import java.util.Collections;
import java.nio.charset.StandardCharsets;

import static gen.TestingCommon.*;
import gen.TestingFramework;

public class MathLogicDiv {
    Logger logger = LoggerFactory.getLogger(MathLogicDiv.class);
    public static final RethinkDB r = RethinkDB.r;

    Connection<?> conn;
    public String hostname = TestingFramework.getConfig().getHostName();
    public int port = TestingFramework.getConfig().getPort();

    @Before
    public void setUp() throws Exception {
        conn = TestingFramework.createConnection();
        try {
            r.dbCreate("test").run(conn);
            r.db("test").wait_().run(conn);
        }catch (Exception e){}
    }

    @After
    public void tearDown() throws Exception {
        System.out.println("Tearing down.");
        if(!conn.isOpen()){
            conn.close();
            conn = TestingFramework.createConnection();
        }
        r.dbDrop("test").run(conn);
        r.db("rethinkdb").table("_debug_scratch").delete();
        conn.close(false);
    }

    // Autogenerated tests below

        @Test(timeout=120000)
    public void test() throws Exception {
                
        {
            // math_logic/div.yaml #(1, 1)
            /* 2 */
            Long expected_ = 2L;
            /* (r.expr(4) / 2) */
            System.out.println("About to run #(1, 1): r.expr(4L).div(2L)");
            Object obtained = runOrCatch(r.expr(4L).div(2L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(1, 1)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(1, 1)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(1, 1):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(1, 2)
            /* 2 */
            Long expected_ = 2L;
            /* (4 / r.expr(2)) */
            System.out.println("About to run #(1, 2): r.div(4L, r.expr(2L))");
            Object obtained = runOrCatch(r.div(4L, r.expr(2L)),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(1, 2)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(1, 2)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(1, 2):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(1, 3)
            /* 2 */
            Long expected_ = 2L;
            /* r.expr(4).div(2) */
            System.out.println("About to run #(1, 3): r.expr(4L).div(2L)");
            Object obtained = runOrCatch(r.expr(4L).div(2L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(1, 3)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(1, 3)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(1, 3):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #2
            /* 0.5 */
            Double expected_ = 0.5;
            /* r.expr(-1) / -2 */
            System.out.println("About to run #2: r.expr(-1L).div(-2L)");
            Object obtained = runOrCatch(r.expr(-1L).div(-2L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #2");
            try {
                assertEquals((double) expected_,
                             ((Number) obtained).doubleValue(),
                             0.00000000001);
            System.out.println("Finished asserting #2");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #2:" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #3
            /* 4.9 / 0.7 */
            Double expected_ = 4.9 / 0.7;
            /* r.expr(4.9) / 0.7 */
            System.out.println("About to run #3: r.expr(4.9).div(0.7)");
            Object obtained = runOrCatch(r.expr(4.9).div(0.7),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #3");
            try {
                assertEquals((double) expected_,
                             ((Number) obtained).doubleValue(),
                             0.00000000001);
            System.out.println("Finished asserting #3");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #3:" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 1)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(1) / 0 */
            System.out.println("About to run #(5, 1): r.expr(1L).div(0L)");
            Object obtained = runOrCatch(r.expr(1L).div(0L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 1)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 1)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 1):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 2)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(2.0) / 0 */
            System.out.println("About to run #(5, 2): r.expr(2.0).div(0L)");
            Object obtained = runOrCatch(r.expr(2.0).div(0L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 2)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 2)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 2):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 3)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(3) / 0.0 */
            System.out.println("About to run #(5, 3): r.expr(3L).div(0.0)");
            Object obtained = runOrCatch(r.expr(3L).div(0.0),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 3)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 3)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 3):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 4)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(4.0) / 0.0 */
            System.out.println("About to run #(5, 4): r.expr(4.0).div(0.0)");
            Object obtained = runOrCatch(r.expr(4.0).div(0.0),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 4)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 4)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 4):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 5)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(0) / 0 */
            System.out.println("About to run #(5, 5): r.expr(0L).div(0L)");
            Object obtained = runOrCatch(r.expr(0L).div(0L),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 5)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 5)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 5):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #(5, 6)
            /* err('ReqlQueryLogicError', 'Cannot divide by zero.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Cannot divide by zero.", r.array(1L));
            /* r.expr(0.0) / 0.0 */
            System.out.println("About to run #(5, 6): r.expr(0.0).div(0.0)");
            Object obtained = runOrCatch(r.expr(0.0).div(0.0),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #(5, 6)");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #(5, 6)");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #(5, 6):" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #6
            /* err('ReqlQueryLogicError', 'Expected type NUMBER but found STRING.', [0]) */
            Err expected_ = err("ReqlQueryLogicError", "Expected type NUMBER but found STRING.", r.array(0L));
            /* r.expr('a') / 0.8 */
            System.out.println("About to run #6: r.expr('a').div(0.8)");
            Object obtained = runOrCatch(r.expr("a").div(0.8),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #6");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #6");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #6:" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
        
        {
            // math_logic/div.yaml #7
            /* err('ReqlQueryLogicError', 'Expected type NUMBER but found STRING.', [1]) */
            Err expected_ = err("ReqlQueryLogicError", "Expected type NUMBER but found STRING.", r.array(1L));
            /* r.expr(1) / 'a' */
            System.out.println("About to run #7: r.expr(1L).div('a')");
            Object obtained = runOrCatch(r.expr(1L).div("a"),
                                          new OptArgs()
                                          ,conn);
            System.out.println("Finished running #7");
            try {
                assertEquals(expected_, obtained);
            System.out.println("Finished asserting #7");
            } catch (Throwable ae) {
                System.out.println("Whoops, got exception on #7:" + ae.toString());
                if(obtained instanceof Throwable) {
                    ae.addSuppressed((Throwable) obtained);
                }
                throw ae;
            }
        }
    }
}
